displayName=GE Trends
author=Yotax
description=Tracks your private GE portfolio and provides live Wiki market lookup from anywhere
tags=grand exchange,investment,portfolio,profit,prices,market
plugins=com.getrends.GeTrendsPlugin
build=standard
